name: Budowanie Konwertera Danych EXE

on:
  schedule:
    - cron: '0 0 * * 0' # Co tydzień w niedzielę o północy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4 # Zaktualizowano do v4 dla spójności

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5 # Zaktualizowano do v5 dla spójności
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          .\installResources.ps1

      - name: Budowanie EXE
        run: |
          pyinstaller --onefile project.py
          pyinstaller --onefile --noconsole project_gui.py

      - name: Przesłanie EXE CLI
        uses: actions/upload-artifact@v4 # Zaktualizowano z v3 na v4
        with:
          name: data-converter-cli
          path: dist/project.exe

      - name: Przesłanie EXE GUI
        uses: actions/upload-artifact@v4 # Zaktualizowano z v3 na v4
        with:
          name: data-converter-gui
          path: dist/project_gui.exe
