name: Budowanie Konwertera Danych EXE

on:
  schedule:
    - cron: '0 0 * * 0' # Co tydzień w niedzielę o północy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Debugowanie środowiska
        run: |
          dir
          python --version
          pip --version
          pip list
        shell: powershell

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          if (Test-Path .\installResources.ps1) {
            Write-Host "Uruchamianie installResources.ps1..."
            .\installResources.ps1
          } else {
            Write-Error "Plik installResources.ps1 nie istnieje!"
            exit 1
          }
        shell: powershell

      - name: Budowanie EXE
        run: |
          pyinstaller --onefile projekt.py
          pyinstaller --onefile --noconsole projekt_gui.py
        shell: powershell

      - name: Przesłanie EXE CLI
        uses: actions/upload-artifact@v4
        with:
          name: data-converter-cli
          path: dist/project.exe

      - name: Przesłanie EXE GUI
        uses: actions/upload-artifact@v4
        with:
          name: data-converter-gui
          path: dist/project_gui.exe
